version: "3.2"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./janus-gateway/html:/app/dist
    ports:
      - "80:80"
      - "443:443"
  janus:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # network_mode: "host"
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8188:8188"
